"""Constants for the WaterCAM integration."""

DOMAIN = "watercam"

CONF_HOST = "host"
CONF_PORT = "port"

DEFAULT_NAME = "Wasserzähler QALCOSONIC W1"
DEFAULT_HOST = "192.168.10.57"
DEFAULT_PORT = 8080

MANUFACTURER = "Axioma"
MODEL = "QALCOSONIC W1 (LifeCam Studio OCR)"
SW_VERSION = "1.1.0"

DEFAULT_INTERVAL = 300
MIN_INTERVAL = 10
MAX_INTERVAL = 86400
STEP_INTERVAL = 5

DEFAULT_FOCUS = 20
DEFAULT_BRIGHTNESS = 133
DEFAULT_EXPOSURE_TIME = 600
